# Generated by Django 4.2.3 on 2023-08-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="work_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.workstation"
            ),
        ),
    ]
